In [1]:
#Name:Leo Jamu
#Date:1/29/2026
#Program of study:Bachelor of Science in computer science
#much passion for data science
# Experiment 7
# Simple Linear regression
#Imagine you're trying to figure out: "How does work experience affect salary?" This notebook answers that question using math

In [2]:
import pandas as pd #python library for analysis and data manipulatio
import os #python library for operating system used to get files if in another directory

In [3]:
os.getcwd()

'F:\\DataScience_Projects\\Training Data Science\\Lesson 7'

In [4]:
data=pd.read_csv("../DataSet/Salary.csv")

In [8]:
data.head() #shows first five people

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [9]:
data.tail() #shows last 5 people

    YearsExperience  Salary
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [10]:
data.describe()  # Shows averages and ranges

       YearsExperience         Salary
count        35.000000      35.000000
mean          6.308571   83945.600000
std           3.618610   32162.673003
min           1.100000   37731.000000
25%           3.450000   57019.000000
50%           5.300000   81363.000000
75%           9.250000  113223.500000
max          13.500000  139465.000000

In [11]:
data.shape #understanding our data,we have 35 people and 2 infor about them(years of experience and salary)

(35, 2)

In [13]:
data.size #returns total records of our datasets(35 records of year of experience and 35 records salaries in our dataset)

70

In [14]:
data.ndim #its a 2d dataset of rows and columns like an excel sheet

2

In [15]:
data.mean() #returns mean of our columns

YearsExperience        6.308571
Salary             83945.600000
dtype: float64

In [16]:
data.columns #returns columns in our data set

Index(['YearsExperience', 'Salary'], dtype='object')

In [17]:
data.isnull() #returns true for rows which have missing value for that column and from our dataset everything is clean

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False
30            False   False
31            False   False
32            False   False
33            False   False
34            False   False

In [18]:
data.sum() #returns sum of records for each column

YearsExperience        220.8
Salary             2938096.0
dtype: float64

In [19]:
x = data.drop('Salary', axis=1)  # X = Experience (what we KNOW)

In [22]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [23]:
y = data.Salary                   # Y = Salary (what we WANT to predict)

In [24]:
y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [ ]:
#Conclusion :-Thus we perform an operation on Simple Linear regression by using Pandas.

# What the Code is ACTUALLY Doing (Behind the Scenes)
#Step 1: Data Preparation
#The computer needs the data in the right format:

#X = Just the experience column

#Y = Just the salary column

#Step 2: Finding the Line
#The computer tries THOUSANDS of different lines and picks the one with the smallest total error.

#What's "error"? How far each dot is from the line.

#Step 3: Making Predictions
#Once it has the "best line," you can ask:

#"What salary for 3 years experience?" → Plug into formula

#"What salary for 7 years experience?" → Plug into formula